version: '3.8'
services:
  dev-postgres:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: man08269055
      POSTGRES_DB: ecdb
    restart: always
    networks:
      - lesson
networks:
  lesson: